package com.skr.fileupload.repository.db.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UPLOAD_FILE_INFO".
*/
public class UploadFileInfoDao extends AbstractDao<UploadFileInfo, Void> {

    public static final String TABLENAME = "UPLOAD_FILE_INFO";

    /**
     * Properties of entity UploadFileInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FilePath = new Property(0, String.class, "filePath", false, "FILE_PATH");
        public final static Property SourceId = new Property(1, String.class, "sourceId", false, "SOURCE_ID");
    }


    public UploadFileInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UploadFileInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UPLOAD_FILE_INFO\" (" + //
                "\"FILE_PATH\" TEXT," + // 0: filePath
                "\"SOURCE_ID\" TEXT);"); // 1: sourceId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UPLOAD_FILE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UploadFileInfo entity) {
        stmt.clearBindings();
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(1, filePath);
        }
 
        String sourceId = entity.getSourceId();
        if (sourceId != null) {
            stmt.bindString(2, sourceId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UploadFileInfo entity) {
        stmt.clearBindings();
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(1, filePath);
        }
 
        String sourceId = entity.getSourceId();
        if (sourceId != null) {
            stmt.bindString(2, sourceId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public UploadFileInfo readEntity(Cursor cursor, int offset) {
        UploadFileInfo entity = new UploadFileInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // filePath
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // sourceId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UploadFileInfo entity, int offset) {
        entity.setFilePath(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSourceId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(UploadFileInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(UploadFileInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(UploadFileInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
